name: match_model
channels:
  - nrel
  - conda-forge
  - defaults
dependencies:
  - cloudpickle
  - glpk
  - ipykernel
  - ipython
  - nbconvert
  - nbformat
  - nrel-pysam==2.2.4 #3.0.0 causes jupyter to crash
  - nrel-pysam-stubs
  - numpy
  - openpyxl
  - pandas
  - pint
  - plotly
  - pyomo>=6.0.0
  - python>=2.7.12
  - pytz
  - pyutilib>=6.0.0
  - requests
  - xlrd