name: switch_pyomo_update
channels:
  - nrel
  - conda-forge
  - defaults
dependencies:
  - cloudpickle
  - glpk
  - ipykernel
  - ipython
  - nbconvert
  - nbformat
  - nrel-pysam
  - nrel-pysam-stubs
  - numpy
  - openpyxl
  - pandas
  - pint
  - plotly
  - pyomo>=6.0.0
  - python>=2.7.12
  - pytz
  - pyutilib
  - requests
  - xlrd