name: match_model
channels:
  - nrel
  - conda-forge
  - defaults
dependencies:
  - cloudpickle
  - glpk
  - ipykernel
  - ipython
  - nbconvert
  - nbformat
  - nrel-pysam<=2.2.4 #lock this until bug with v3.0.0 is fixed https://github.com/NREL/pysam/issues/107
  - nrel-pysam-stubs
  - numpy
  - openpyxl
  - pandas
  - pint
  - plotly
  - pyomo>=6.0.0
  - python>=2.7.12
  - pytz
  - pyutilib>=6.0.0
  - requests
  - xlrd