name: switch_247
channels:
  - nrel
  - conda-forge
  - defaults
dependencies:
  - cloudpickle
  - glpk
  - ipykernel
  - ipython
  - nbconvert
  - nbformat
  - nrel-pysam
  - nrel-pysam-stubs
  - numpy
  - openpyxl
  - pandas
  - pint
  - plotly
  - pyomo<=5.6.8
  - python>=2.7.12
  - pytz
  - pyutilib<=5.7.3
  - requests
  - xlrd